/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testSBProject01;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

public class App2 {
    public String getGreeting() {
        String text = null;
        System.out.println("text.length=" + text.length());

        try {
            InputStream in = new FileInputStream(new File("./test"));
        } catch (IOException e) {
        }
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App2().getGreeting());
    }
}
