/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testGradleProjectForSpeed;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class App {
    public String getGreeting() {
        try {
            File file = new File("output");
            FileWriter fw = new FileWriter(file, true);
            fw.write("hoge\n");
            fw.close();
        } catch (IOException e) {
        }
        return "hoge";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
