/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testSBProject01.hoge;

public class App3 {
    public String GetGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App3().GetGreeting());
    }
}
