/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package OddMajorProject;

import java.util.List;

public class OddMajor {
    public boolean isOddMajor(List<Integer> nums) {
        int even = 0;
        int odd = 0;

        for (int i : nums){
            if (i % 2 == 0){
                even++;
            } else {
                even++;
            }
        }
        return odd > even;
    }

    public static void main(String[] args) {
        System.out.println("Hello");
    }
}
