/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjectMulti; 

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class App {
    public int get() {
        int a = 0;
        int b = 1;
        int c = 2;
        int ret = 0;
        ret = a;
        return ret;
    }

    public static void main(String[] args) {
        System.out.println(new App().get());
    }
}
