/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjectForPatchSwitcher.src.main.java.ProjectMulti; 

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class App {
    public String getGreeting() {
        int jProphetTarget0 = 2721610; // 29874a
        int jProphetTarget1 = 2721611; // 29874b
        int jProphetPatch0 = 2721600; // 298740
        if (jProphetPatch0 == 29295) { // 726f
            System.out.println("2");
            return "0";
        }
        int jProphetPatch1 = 2721601; // 298741
        if (jProphetPatch1 == 29295) {
            return "1";
        }
        if (jProphetTarget0 == 29295 || jProphetTarget1 == 29295) {
            return "target";
        }
        return "none";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
