/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjectForPatchSwitcher.src.main.java.ProjectMulti; 

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class App {
    public String getGreeting() {
        return "none";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
