/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jcc;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest implements Runnable {
    @Test public void testiftest() {
        iftest classUnderTest = new iftest();
        assertNotNull("app should have a greeting", classUnderTest.suuji(1));
    }
    public void run(){
        assertNotNull("app should have a greeting", new iftest().suuji(0)); 
    }
    /*
    @Test public void testiftest2() {
        iftest classUnderTest = new iftest();
        assertNotNull("app should have a greeting", classUnderTest.suuji(2));
    }
    */
    @Test public void testiftest3() {
        iftest classUnderTest = new iftest();
        assertNotNull("app should have a greeting", classUnderTest.suuji(2));
    }
}
