/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jcc;

import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testiftest() {
        iftest classUnderTest = new iftest();
        assertNotNull("app should have a greeting", classUnderTest.suuji(1));
    }
}
