/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jcc;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testiftest() {
        assertEquals(1, new iftest().printNum(1));
    }
    @Test public void testiftest2() {
        assertEquals(2, new iftest().printNum(2));
    }
    @Test public void testiftest3() {
        assertEquals(3, new iftest().printNum(3));
    }
}
