/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package OddMajorProject;

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.List;

public class OddMajorTest {
    OddMajor oddMajor = new OddMajor();
    @Test public void testAppHasAGreeting() {
        List<Integer> list = new ArrayList<Integer>();
        list.add(2);
        list.add(1);
        list.add(3);
        list.add(4);
        oddMajor.isOddMajor(list);
        System.out.println(list);
    }
}
