/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BubbleSortProject;

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.Arrays;

public class BubbleSortTest {
    BubbleSort qSort = new BubbleSort();
    
    @Test public void testAppHasAGreeting8() {
        int value[] = {1, 3, 2};
        int collect[] = {1, 2, 3};
        qSort.sort(value);
        assertTrue(Arrays.equals(collect, value));
    }

    @Test public void testAppHasAGreeting6() {
        int value[] = {1, 2, 3};
        int collect[] = {1, 2, 3};
        qSort.sort(value);
        assertTrue(Arrays.equals(collect, value));
    }

}
