/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testSBProject02;

public class RoughConstantValue {
    public double calcCicleArea(double radius) {
        double pi = Math.PI;       //定義済みライブラリ定数
        double area = radius * 2;
        area *= 3.141592;        //雑な値　ここでワーニングが発生するはず
        //areaに代入する値をpiに置き換えられればワーニングは解消する
        return area;
    }

    public static void main(String[] args) {
        final RoughConstantValue roughConstantValue = new RoughConstantValue();
        System.out.println(roughConstantValue.calcCicleArea(5));
    }
}
