/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjectMulti; 

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class App {
    public String getGreeting() {
        int flag = 699;
        try {
            File file = new File("output-multi");
            FileWriter fw = new FileWriter(file, true);
            if (flag == 699) {
                fw.write("hoge699\n");
                fw.close();
                return "hoge";
            }
            if (flag == 933) {
                fw.write("fuga933\n");
                fw.close();
                return "fuga";
            }
        } catch (IOException e) {
            //TODO: handle exception
        }
        return "null";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
