/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BynarySearchProject;

import org.junit.Test;
import static org.junit.Assert.*;

public class BynarySearchTest {
    BynarySearch bynarySearch = new BynarySearch();
    @Test public void testAppHasAGreeting() {
        int value[] = {1, 2, 3, 4, 5};
        int target = 4;
        int index = bynarySearch.search(value, target);
        assertTrue(index == 3);
    }

    @Test public void testAppHasAGreeting2() {
        int value[] = {1};
        int target = 1;
        int index = bynarySearch.search(value, target);
        assertTrue(index == 0);
    }

    @Test public void testAppHasAGreeting3() {
        int value[] = {1, 2, 3, 4, 5};
        int target = 6;
        int index = bynarySearch.search(value, target);
        assertTrue(index == -1);
    }

    @Test public void testAppHasAGreeting4() {
        int value[] = {1, 2, 3, 4};
        int target = 2;
        int index = bynarySearch.search(value, target);
        assertTrue(index == 1);
    }
}
