/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HeapSortProject;

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.Arrays;

public class HeapSortTest {
    HeapSort qSort = new HeapSort();
    
    

    

    @Test public void testAppHasAGreeting1() {
        int value[] = {1, 3, 2};
        int collect[] = {1, 2, 3};
        qSort.sort(value);
        assertTrue(Arrays.equals(collect, value));
    }

    @Test public void testAppHasAGreeting2() {
        int value[] = {2, 1};
        int collect[] = {1, 2};
        qSort.sort(value);
        assertTrue(Arrays.equals(collect, value));
    }

    @Test public void testAppHasAGreeting3() {
        int value[] = {1, 3, 4, 2};
        int collect[] = {1, 2, 3, 4};
        qSort.sort(value);
        assertTrue(Arrays.equals(collect, value));
    }

    @Test public void testAppHasAGreeting4() {
        int value[] = {1, 2, 3, 4};
        int collect[] = {1, 2, 3, 4};
        qSort.sort(value);
        assertTrue(Arrays.equals(collect, value));
    }

    @Test public void testAppHasAGreeting5() {
        int value[] = {4, 3, 2, 1};
        int collect[] = {1, 2, 3, 4};
        qSort.sort(value);
        assertTrue(Arrays.equals(collect, value));
    }
}
